### ISSUE TITLE
TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by kepamuk** [cloverhearts/quilljs-markdown#20]
when i try use this

import Quill from 'quill'
import QuillMarkdown from 'quilljs-markdown'

const editor = new Quill('#editor', {})
new QuillMarkdown(editor)

I get this error 
![image](https://user-images.githubusercontent.com/11090297/100132558-a5689a00-2e96-11eb-9432-00d8d706f0a1.png)

**Comment by cloverhearts** [comment]
Hello @kepamuk 
What's your version of Quilljs?
I'll check it soon from your answers.

**Comment by kepamuk** [comment]
"quill": "^1.3.7",
    "quilljs-markdown": "^1.0.3",

**Comment by cloverhearts** [comment]
Thank you.
I'll check soon.

**Comment by kepamuk** [comment]
I need to use this component for a react, can you tell me how to do this?

**Comment by cloverhearts** [comment]
Maybe, I found problem.

## How to reproduce this problem?
if does not wrap the quilljs object with `DOMContetloaded` event handler.
then occurs this problem. 
`invalid quilljs`

so, this is not a bug of quilljs-markdown.
you can try this and refer to another code.

```
import Quill from 'quill'
import QuillMarkdown from 'quilljs-markdown'

document.addEventListener('DOMContentLoaded', function() {
    const editor = new Quill('#editor', {})
    new QuillMarkdown(editor)
})

```

https://github.com/cloverhearts/quilljs-markdown/blob/master/docs/demo.js#L8

**Comment by cloverhearts** [comment]
React component is not related this library.
but, in my opinion this document is give good idea to you.

https://github.com/zenoamaro/react-quill#api-reference
```
// ES6
import ReactQuill, {Quill} from 'react-quill';

// CommonJS
const ReactQuill = require('react-quill');
const {Quill} = ReactQuill;

new QuillMarkdown(Quill)

```

**Comment by cloverhearts** [comment]
Please check for this issue. and close.

**Comment by cloverhearts** [comment]
@kepamuk

**Comment by cloverhearts** [comment]
I'll close after 1 week about this issue.

**Comment by kepamuk** [comment]
```
import React from 'react';
import Quill from 'quill'
import QuillMarkdown from 'quilljs-markdown'



function App() {
  const editor = new Quill('#editor', {})
  new QuillMarkdown(editor)
  
  return (
    <div className="App">
      <div id="editor"/>
    </div>
  );
}

export default App;
```

this is my code where i get error

**Comment by kepamuk** [comment]
> React component is not related this library.
> but, in my opinion this document is give good idea to you.
> 
> https://github.com/zenoamaro/react-quill#api-reference
> 
> for example (doesn't tested)
> 
> ```
> // ES6
> import ReactQuill, {Quill} from 'react-quill';
> 
> // CommonJS
> const ReactQuill = require('react-quill');
> const {Quill} = ReactQuill;
> 
> new QuillMarkdown(Quill)
> ```

![image](https://user-images.githubusercontent.com/11090297/100500950-932f7a00-317c-11eb-8043-5689ecef39e6.png)

**Comment by cloverhearts** [comment]
![image](https://user-images.githubusercontent.com/10525473/100582322-6d48d780-332c-11eb-93bf-e3b916c2899e.png)


@kepamuk 
Does well work.
You can research to the effect and ref hooks in react.

**Comment by kepamuk** [comment]
> ![image](https://user-images.githubusercontent.com/10525473/100582322-6d48d780-332c-11eb-93bf-e3b916c2899e.png)
> 
> @kepamuk
> Does well work.
> You can research to the effect and ref hooks in react.

thank you this work, but can you tall how to do this with react-quill ? https://www.npmjs.com/package/react-quill

**Comment by kepamuk** [comment]
`import React, {useEffect, useState} from 'react';
import ReactQuill, {Quill} from 'react-quill';
import QuillMarkdown from 'quilljs-markdown';


function App() {
  const [val, valSet] = useState('');
  const [ed, edSet] = useState('');

  const handleChange = (value) => {
    valSet(value)
  }

  const editorRef = ed.editor

  useEffect(()=>{
    if(editorRef){
      const editorEle = editorRef.container
      const editor = new Quill(editorEle, {theme: 'snow'})
      new QuillMarkdown(editor)
    }
  },[editorRef])

  return (
    <div className="App">
      <ReactQuill
        value={val}
        onChange={handleChange}
        ref={(el) => edSet(el)}
      />
    </div>
  );
}

export default App;`

I got this, but for some reason the component is duplicated
![image](https://user-images.githubusercontent.com/11090297/100685648-d7459900-338d-11eb-80fc-5ccdd7a4ef21.png)

**Comment by cloverhearts** [comment]
I don't know regarding react-quill module.
perhaps, you can ask your problems to react-quill community or another community.

Thanks :)

**Comment by Pareder** [comment]
@kepamuk and those trying to integrate this plugin into `react-quill` I have found the solution. You can pass ref to `ReactQuill` component and this ref will have `getEditor` method. Call it and pass to `QuillMarkdown`.

```
import { useEffect, useRef } from 'react'
import ReactQuill from 'react-quill'
import QuillMarkdown from 'quilljs-markdown'

export default function QuillInput(props) {
  useEffect(() => {
    new QuillMarkdown(quill.current.getEditor?.())
  }, [])

  return (
    <ReactQuill
      {...props}
      ref={quill}
    />
  )
}
```

**Comment by cloverhearts** [comment]
NICE!
