### ISSUE TITLE
Ignore tags not work.

### ISSUE THREAD

**Issue by saiddjelmo** [cloverhearts/quilljs-markdown#28]
Ignore tags not work. In app.js function isValid don't pass correct tagName.

**Comment by cloverhearts** [comment]
I'll check it at tonight.

**Comment by cloverhearts** [comment]
@saiddjelmo 
Could you explain your problem?
Or you can upload your test code about this issue.

**Comment by cloverhearts** [comment]
Things we need.
Intentions,
Expected,
Measured.

**Comment by saiddjelmo** [comment]
I need ignore some tags, for example tags (h1, h2, h3, h4, h5, h6). 
In option I passed ignoreTags.
```
const markdownOptions = {
      ignoreTags: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'],
      tags: {
        bold: {
          pattern: /(\*){1}(.+?)(?:\1){1}/g,
        },
        italic: {
          pattern: /(\_){1}(.+?)(?:\1){1}/g,
        },
      },
    };
    const markdown = new QuillMarkdown(this.editor, markdownOptions);
```

When I'm typing:  # text, I got  `<h1>text</h1>`. It not ignore H1 tag, but it should be, becouse I have in ignoreTags H1.
I think problem is in app.js in onInlineExecute() function. It checking is tag valid with function isValid() and send as params text and Object line.domNode.tagName, but  line.domNode.tagName is p insted of h1.

**Comment by cloverhearts** [comment]
Ah, i had understood your goal.
I'll consider to variable option method based on your idea.

**Comment by cloverhearts** [comment]
I was replace your code now.
You did write your code are evaluate for ignore tags at app.js
but me replace to position of each tag class for ignore evaluate code logic.

For example
```
// app.js
constructor(option) {
  this.ignoreTags = option.ignore ...
}

  isValid (text, tagName) {
    console.log('text ', text, tagName)
    return (
      typeof text !== 'undefined' &&
      text &&
      !this.ignoreTags.find(e => e === tagName)
    )
  }

```
Replace to...

app.js
```
constructor(option) {
  this.tags = new TagsOperators(this.quillJS, options)
}

```

Header.js
```

constructor(option) {
  this.activeTags = supportHtmlTags - option.ignoreTags
}

supportHtmlTgas() {
  return ['h1', 'h2' ]
}

getActions(actionTag) {
  if (this.activeTags.includes(actionTag) {
    return false // stop
  }
}

```

Your code have nice idea.
I would be grateful if you would accept me positively for changing your code.

**Comment by cloverhearts** [comment]
![image](https://user-images.githubusercontent.com/10525473/107149318-45fd2f00-699b-11eb-9ff5-9e49ef3e539d.png)

**Comment by cloverhearts** [comment]
Completed
