### ISSUE TITLE
Improve nested list styling

### ISSUE THREAD

**Issue by IllusionVK** [cloverhearts/quilljs-markdown#30]
Thanks so much for your work on this!

We have only just started to use this extension, and wondering if more sophisticated nested lists are possible?  for example like https://jsfiddle.net/c4v608ty/1/

This shows 3 main benefits:
-  the top level bullet icon is larger than in quilljs-markdown, and 
-  the nested bullets are different based on the nesting level.
-  the indentation level is a little bit different to the quilljs-markdown indentation which is better because it uses less space

I'm not sure if there are limitations imposed by quill, but if something like this were possible it would be awesome.  Thanks for considering!

**Comment by cloverhearts** [comment]
Quilljs seems to have limitations in displaying lists with depth.
For example:
```
<ul>
  <li>1 depth</li>
  <li>1 depth</li>
  <li>
    <ul>  <-- ul in li tag
      <li>
        2 depth
      </li>
      <li>
        2 depth
      </li>
    </ul>
  </li>
</ul>

```

but quilljs is here

```

<ul>
  <li class="ql-indent-1">1 depth</li> <-- li depth is 1 in html tag. but, seems to be 2depth in browser ui
  <li class="ql-indent-1">1 depth</li>
  <li class="ql-indent-2">2 depth</li>
  <li class="ql-indent-2">2 depth</li>
</ul>

```

But your opinion is right.
So, I'll fix it in a possible way in the quilljs-markdown area

**Comment by cloverhearts** [comment]
![image](https://user-images.githubusercontent.com/10525473/109413827-cc34f000-79f2-11eb-8bd7-31a2d9746c17.png)

Replaced

**Comment by cloverhearts** [comment]
before
![image](https://user-images.githubusercontent.com/10525473/109413855-ebcc1880-79f2-11eb-8b95-80b6db581e20.png)

**Comment by cloverhearts** [comment]
Large font

**Comment by cloverhearts** [comment]
Ready for merge https://github.com/cloverhearts/quilljs-markdown/pull/31

**Comment by IllusionVK** [comment]
Wow @cloverhearts, Legend !
