### ISSUE TITLE
markdown link not working

### ISSUE THREAD

**Issue by andrewhemans** [cloverhearts/quilljs-markdown#33]
expected: when typing a link in markdown format `[link text](www.link.com)` the link should show in the editor.

actual behavior: after typing the link in markdown format when you type a space or return the link text gets corrupted.

<img width="208" alt="Screen Shot 2021-03-17 at 2 12 08 PM" src="https://user-images.githubusercontent.com/16245896/111539317-fc86c900-872a-11eb-9d9d-22ea3b329fe5.png">

<img width="460" alt="Screen Shot 2021-03-17 at 2 12 32 PM" src="https://user-images.githubusercontent.com/16245896/111539327-ff81b980-872a-11eb-9513-130b12c01e35.png">

**Comment by cloverhearts** [comment]
I'll check it soon.
Thank you your report :)

**Comment by cloverhearts** [comment]
@andrewhemans 
Ready PR for this.
I'll merge to at tomorrow and publish version 1.1.4.

**Comment by andrewhemans** [comment]
Awesome thank you!

**Comment by ashikraj78** [comment]
Does it necessary to include " https://" before any website name . 
Please check into it

**Comment by cloverhearts** [comment]
Currently, no problem.
[Hello](#hello) // okay.
[Hello](https://hello) // okay.
[Hello](empty) // okay.
