### ISSUE TITLE
can't jump out of the input when using  ```

### ISSUE THREAD

**Issue by littleweb** [cloverhearts/quilljs-markdown#35]
can't jump out of the input when using ```

**Comment by cloverhearts** [comment]
You can input the enter key * 3
![example](https://user-images.githubusercontent.com/10525473/116085129-740c2880-a6d9-11eb-8797-f69775ef0602.gif)

**Comment by littleweb** [comment]
thanks，but input > can't jump out

**Comment by cloverhearts** [comment]
@littleweb 
Yes, i just found it.
i'll fix with this issue.
https://github.com/cloverhearts/quilljs-markdown/issues/36

**Comment by cloverhearts** [comment]
Thank you for your report

**Comment by littleweb** [comment]
Inline code has the same problem.

**Comment by littleweb** [comment]
For reference
https://codepen.io/DmitrySkripkin/pen/KZWZxJ

**Comment by cloverhearts** [comment]
Ready for merge #38

**Comment by cloverhearts** [comment]
Merged
