### ISSUE TITLE
Breaks History and Blockquotes

### ISSUE THREAD

**Issue by azumbrunnen** [cloverhearts/quilljs-markdown#36]
This is overall really solid however, there is two issues that would make me shy away from it in a production environment:

1. when you create "- + space" it creates a list, but if you want to undo it, you're stuck in an infinite undo / redo of your plugin and quilll native behavior
2. when you create "> + space" on an empty line it works as expected. On a line that already has content on the other hand, putting the cursor at the beginning and writing "> + space" will result in an immediate undo operation and the blockquote disappears.

Any chances for a fix there?

**Comment by cloverhearts** [comment]
Oh.. yes. you are right.
I think strange about editor's behavior on your explains.
I'll fix it and more to adjust this.

**Comment by cloverhearts** [comment]
Thank you for your report

**Comment by cloverhearts** [comment]
Ready for merge #38

**Comment by cloverhearts** [comment]
> when you create "- + space" it creates a list, but if you want to undo it, you're stuck in an infinite undo / redo of your plugin and quilll native behavior

case of first.
I think little bit confused policy of markdown syntax.
I'll consider about this problem.
Thank you.
