### ISSUE TITLE
Disable markup inside certain tags? ( additional problem )

### ISSUE THREAD

**Issue by c0ldst0rage** [cloverhearts/quilljs-markdown#45]
Hi, and thanks for the fix for disabling markup inside \<code\>\<\/code\>.

However, there is still one issue...

If you copy some text with underscores and paste this directly into an existing \<code\>\<\/code\>, the markup is still actioned before it is pasted between the \<code\>\<\/code\> tags. This is one of the most likely things to do, so the error popped up quickly.

Thanks in advance for taking a look at this. ;o)

**Comment by c0ldst0rage** [comment]
I see that you implemented pasting recently? Back in January... 
So I guess (maybe) a simple exclusion needs adding to the pasting code? ;o)

**Comment by cloverhearts** [comment]
Hmm I'll check it.

**Comment by c0ldst0rage** [comment]
Thanks for looking into these issues / suggestions!

**Comment by c0ldst0rage** [comment]
The original bug is still present... ( sorry! )

If you create a <code> section on an empty line or in an empty editor, all works 100%.

But, if you create a <code> section in the middle of some existing text, using underscores will cause the text to become italicized.

**Comment by cloverhearts** [comment]
I will try to reproduce based on your comments.

**Comment by cloverhearts** [comment]
I'll upload PR at today
