### ISSUE TITLE
Some (Block-level?) html elements break markdown shortcuts

### ISSUE THREAD

**Issue by Matoo125** [cloverhearts/quilljs-markdown#46]
Steps to replicate
1. Open https://codepen.io/Matoo125/pen/yLoQGbg?editors=1111
2. Insert image
3. Try to create bold test such as **bold** by typing

Anything below image will not parse bold correctly (it will parse as italic). The same issue is with other block-level elements I tried such as divs and `<hr>`
![Screenshot from 2021-11-16 10-52-54](https://user-images.githubusercontent.com/10489019/141962846-eb9a0393-6e1a-44f3-9754-9572c2ee5dd0.png)

**Comment by cloverhearts** [comment]
oh my god

**Comment by cloverhearts** [comment]
I'll upload PR at today

**Comment by Matoo125** [comment]
Wonderful, thank you. You are very fast! :)

**Comment by cloverhearts** [comment]
Ready for PR
