### ISSUE TITLE
Disable markdown on-the-fly

### ISSUE THREAD

**Issue by jfhr** [cloverhearts/quilljs-markdown#50]
Hi, I'd like to give my users the ability to enable/disable markdown support on-the-fly. 

When markdown is enabled, I just call `new QuillMarkdown(quill)`, which works fine.

But I haven't found a way to disable it on the fly. `delete`ing the `QuillMarkdown` instance doesn't seem to work. We'd probably have to remove the event listeners added in the constructor.

Is there any support for that? Thanks!

**Comment by cloverhearts** [comment]
It's a amzaing idea!
