### ISSUE TITLE
add QuillMarkdown to quill.modules{}

### ISSUE THREAD

**Issue by eng-dibo** [cloverhearts/quilljs-markdown#54]
I see in [your examples](https://cloverhearts.github.io/quilljs-markdown/) that you enable QuillMarkdown this way `new QuillMarkdown(editor, markdownOptions)`, the standard method to enable it like this 
```
Quill.register('modules/QuillMarkdown',QuillMarkdown,true)

new quill('#editor', {
 modules: {
    QuillMarkdown: { /*options*/ }
  }
});
```

I tested it this way and it works

**Comment by cloverhearts** [comment]
Nice! I'll add to doc as soon. Thank you :)
