### ISSUE TITLE
The markdown syntax for creating a link does not automatically convert into an expected link

### ISSUE THREAD

**Issue by DykiSA** [cloverhearts/quilljs-markdown#57]
Step to reproduce:
1. Write (**don't copy paste**) `[here](https://example.com)` inside the editor
2. It does not turn into a link as how the editor works with the original link button

> In the other case, when you undo some steps backward after typing that syntax, it will turn into a link as what is expected.

![image](https://user-images.githubusercontent.com/17403009/166458087-932f6dae-e9da-4559-a28b-e2c51079fb5f.png)

**Comment by cloverhearts** [comment]
I can reproduce this bug.
I'll fix it soon.

Thank you for your report!
