### ISSUE TITLE
ERROR on iOS device: Unhandle promise rejection: null is not a funtion

### ISSUE THREAD

**Issue by zmaximo1990** [cloverhearts/quilljs-markdown#64]
When open the webpage on browser of an iOS device, it gets stuck and user can't interact with.

https://user-images.githubusercontent.com/7076329/176960294-8b6b6728-c43d-4fa4-9043-abdcc5dd9a7c.mp4

Here the iOS Chrome inspector error:
![WhatsApp Image 2022-07-01 at 1 45 37 PM](https://user-images.githubusercontent.com/7076329/176960452-7dcbe7f8-1b65-45d5-b3a7-1f7af72e231d.jpeg)

The error is shown when the app loads. 

Without **quilljs-markdown** installed everything works fine.

In Android or desktop devices it works fine.

Angular 7
Quill 1.3.7
NgxQuill 7.3.1

**Comment by zmaximo1990** [comment]
Great @cloverhearts!

Please, let me know ASAP you release the bugfix.

Nice package 💪!

Thanks a lot!

**Comment by cloverhearts** [comment]
hmm... i can't reproduce your problem.
I tested on ios version 15.x and mobile safari.
but, does well work on my device with official quill markdown website and ineco-u.com
(my web inspector does not shown any errors, especially null problem not occurs on website when input keyboard time.)

@zmaximo1990  could you give me more information about this problem?

**Comment by cloverhearts** [comment]
Okay, I'll check it on today.

**Comment by cloverhearts** [comment]
Hello. @zmaximo1990 
Can you try this tag with editor html tag on app.component.html file?
And thank you for commenting on the results.
` translate="no"`
```
<quill-editor #quillEditorCmp [modules]="config" translate="no"></quill-editor>
```

![image](https://user-images.githubusercontent.com/10525473/178409673-140d21b1-0571-47f1-93f8-916113d5a217.png)

**Comment by zmaximo1990** [comment]
@cloverhearts sorry by delay.

I didn't work.
Now this error is thrown.

![WhatsApp Image 2022-07-14 at 10 52 10 AM](https://user-images.githubusercontent.com/7076329/179036955-5ee9e41b-e3e4-4e66-8859-59f1cdb071ec.jpeg)

I think the problem is other on iOS but i don't know what is causing it. As i mentioned before using vanilla HTML instalation you provided works fine. The problems appear when `quilljs-markdown` is installed from `npm` and imported using ECMAScript modules.

**Comment by cloverhearts** [comment]
<img width="415" alt="image" src="https://user-images.githubusercontent.com/10525473/179410731-03b7fcfc-cbc7-4770-a7d1-40eaf95c2ed2.png">

Okay fixed.
problem are core-js
i'll remove corejs when next release.
