### ISSUE TITLE
not compatible with SSR

### ISSUE THREAD

**Issue by eng-dibo** [cloverhearts/quilljs-markdown#65]
I use quill in a universal Angular app, and want to render the form in server-side

this line `Quill.register({ 'modules/QuillMarkdown': QuillMarkdown }, true);` causes the error `Uncaught (in promise): ReferenceError: document is not defined`

**Comment by cloverhearts** [comment]
quilljs-markdown cannot support SSR.
because Quilljs support only browser side.
do you have any opinions? 

Thank you :)

**Comment by eng-dibo** [comment]
I already use quilljs in ssr without any problem, the problem in quilljs-markdown is caused by using `document` which is browser-specific.

document should be provided by Angular to be available in both browser and server sides.

a temporary workaround is to allow the consumer to pass the provided document to the plugin options.

**Comment by cloverhearts** [comment]
Hmm Okay, i check to more information about this.

**Comment by cloverhearts** [comment]
This will break support for older browsers, including ie11, but this can be fixed by adding core-js separately.

**Comment by eng-dibo** [comment]
ie11 is [not supported by Angular](https://angular.io/guide/browser-support) nor major front-end frameworks

**Comment by its-dibo** [comment]
worked! <3
