### ISSUE TITLE
Can't get Italic, Bold & Strikethrough to work

### ISSUE THREAD

**Issue by RPerkins96** [cloverhearts/quilljs-markdown#67]
Just started to use the project and found that bold, strikethrough, and italics are not recognized using 
**text**      or
__text__    or
~~text~~  *text*

Oddly _text_ (optional italic syntax) does work, in that when the second underscore is typed, the word text becomes italicized.
This behavior can be seen in the playground, so may not be connected to my usage.

**Comment by cloverhearts** [comment]
Hello, what happen about your problem?
Was that a solved?
