### ISSUE TITLE
use this package in the browser

### ISSUE THREAD

**Issue by its-dibo** [cloverhearts/quilljs-markdown#68]
I use this package as a node package and it works, but I need to load it in the browser
here are my trials:

```
import("/node_modules/quilljs-markdown/index.js").then(QuillMarkdown=>Quill.register(...))
```

this causes an error because it imports from './src/app.js' which includes `import 'regenerator-runtime'`
the paths in the browser should be relative `/node_modules/regenerator-runtime`

```
// load a normal javascript file
 load( "/node_modules/quilljs-markdown/dist/quilljs-markdown.js" ).then(()=>{
  console.log(window.QuillMarkdown) // function
 Quill.register({ "modules/QuillMarkdown": window.QuillMarkdown }, true)
})
```
this causes the error `quill Cannot import modules/QuillMarkdown. Are you sure it was registered?`

the same behavior when loading from CDN
```
load("https://cdn.jsdelivr.net/npm/quilljs-markdown@latest/dist/quilljs-markdown.js").then(...)

**Comment by cloverhearts** [comment]
![image](https://user-images.githubusercontent.com/10525473/204415947-13af0345-09e8-4fd5-8fd6-ad97dcb413ce.png)
Currently, I used official landing page for quilljs-markdown page with jsdelivr cdn. 
https://cloverhearts.github.io/quilljs-markdown/

**Comment by cloverhearts** [comment]
You can try on this
```
<script src="https://cdn.jsdelivr.net/npm/quilljs-markdown@latest/dist/quilljs-markdown.js"><script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/quilljs-markdown@latest/dist/quilljs-markdown-common-style.css" />
<script>
  document.addEventListener('DOMContentLoaded', () => {
    var quill = new Quill('#editor', {
    theme: 'snow'
  });
  new QuillMarkdown(editor) // window.QuillMarkdown
})
<script>
```

QuillMarkdown Object are set up to window global object.

![image](https://user-images.githubusercontent.com/10525473/204436028-b25e399f-0655-4db2-93db-c80f968c0f91.png)


setup code is here
https://github.com/cloverhearts/quilljs-markdown/blob/84c80fee7d94bc2b027660e258137db7252e8f07/index.js#L4
