### ISSUE TITLE
[기능개선] markdown 구문 추가가 필요합니다.

### ISSUE THREAD

**Issue by wecanooo** [cloverhearts/quilljs-markdown#9]
다음과 같은 기능이 추가로 있었으면 좋겠습니다.

1. Blockquotes
2. Inline code
3. Syntax highlighting

https://guides.github.com/features/mastering-markdown/

**Comment by cloverhearts** [comment]
https://github.com/cloverhearts/quilljs-markdown/pull/10

working in progress

**Comment by cloverhearts** [comment]
sovled
